### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by take2rohit** [lineojcd/UCR-EE283-2022-Fall-Analytical-Project#1]
- [x] Change the image 
- [x] Add a description of the project
- [x] How to run codes/code description
- [x] Upload all the `src` @lineojcd
